version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3111:3000
    volumes:
      - type: bind
        source: .
        target: /src
        consistency: delegated
    env_file:
      - .env.local
    environment:
      - WATCHPACK_POLLING=true
    entrypoint: docker/entrypoint.sh
    command: yarn dev
