name: CI
on: [push]
jobs:
  test:
    runs-on: normal
    container:
      image: node:16.13.0
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install packages
        run: yarn install
      - name: run test
        run: yarn test
