name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install packages
        run: yarn install
      - name: run test
        run: yarn test --passWithNoTests
